[build]
  publish = "dist"
  command = "npm run build"

[[edge_functions]]
  path = "/api/yahoo-quote"
  function = "yahoo-quote"

[[edge_functions]]
  path = "/api/yahoo-chart"
  function = "yahoo-chart"

[[edge_functions]]
  path = "/api/yahoo-html/quote/*"
  function = "yahoo-html"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
